public class Main {
    public static void main(String[] args) {
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        var x = 4;
        dog = dog + x;
        System.out.println(dog);
        cat = cat + x;
        System.out.println(cat);
        paper = paper + x;
        System.out.println(paper);
        dog = dog - 3.5;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 3;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var firstBoxer = 78.2;
        var secondBoxer = 82.7;
        var totalWeight = firstBoxer + secondBoxer;
        System.out.println("Общий вес обоих боксеров: " + totalWeight);
        var differenceOfWeight = secondBoxer - firstBoxer;
        System.out.println("Разница в весе боксеров: " + differenceOfWeight);
        var remainder = secondBoxer % firstBoxer;
        System.out.println("Остаток от деления между двумя весами: " + remainder);
        var totalTime = 640;
        var employeeTime = 8;
        var numberOfEmployees = totalTime / employeeTime;
        System.out.println("В компании, при проекте, требующим " + totalTime + " часов, в который каждый сотрудник вкладывает " + employeeTime + " часов, работает " + numberOfEmployees + " сотрудников");
        numberOfEmployees = numberOfEmployees + 94;
        employeeTime = totalTime / numberOfEmployees;
        System.out.println("Если в компании работает " + numberOfEmployees + " человека, то всего " + employeeTime + " часа работы может быть поделено между сотрудниками");
    }
}